name = "tokyonight"
license = "ISC"
licenselink = "https://en.wikipedia.org/wiki/ISC_license#OpenBSD_license"
description = "Tokyo Night Hugo Theme"
homepage = "https://thesemicolons.com/"
tags = ["blog"]
features = ["blog"]
min_verseion = "0.1"

[author]
  name = "James Anderson"
  homepage = "https://thesemicolons.com"
